version: '3.8'

services:
  snake-game:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: snake-game-demo
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - snake-network

networks:
  snake-network:
    driver: bridge